### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by Yonjuni** [SecUSo/privacy-friendly-battleship#2]
Please keep in mind to update the Readme

**Comment by Korb** [comment]
@AlexanderMlr, [Google Play link](https://play.google.com/store/apps/details?id=org.secuso.privacyfriendlybattleship):

> We're sorry, the requested URL was not found on this server.
> 404 Not Found

There is not a single screenshot of the application and its settings. Will you add?

**Comment by 0xC0FFEEC0DE** [comment]
The PFA apps get removed from Google play store soon. Please have a look at F-Droid and its app store: [Schiffe versenken (Privacy Friendly)](https://f-droid.org/packages/org.secuso.privacyfriendlybattleship/).
